import type { Metadata } from "next";
import { Inter, Poltawski_Nowy, JetBrains_Mono } from "next/font/google";

import { AppProvider } from "@/components/commons/AppProvider";
import { cn } from "@/lib/utils/cn";

import "./globals.css";

const poltawskiNowy = Poltawski_Nowy({
  subsets: ["vietnamese"],
  variable: "--font-poltawski-nowy",
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["vietnamese"],
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["vietnamese"],
});

export const metadata: Metadata = {
  title: "BOOKSHOP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        inter.variable,
        poltawskiNowy.variable,
        jetBrainsMono.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
